apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  # Ambiente da aplicação
  ASPNETCORE_ENVIRONMENT: "Production"

  # URLs de outros microsserviços (exemplos)
  USERS_API_URL: "http://users-api:80"
  PAYMENTS_API_URL: "http://payments-api:80"

  # Configurações internas da aplicação
  DEFAULT_PAGE_SIZE: "20"
  MAX_PAGE_SIZE: "100"

  # Nome de filas/tópicos do RabbitMQ, se usar
  RABBITMQ_QUEUE: "catalog_queue"